load("//examples:example_build.bzl", "roo_windows_example")

roo_windows_example(
    name = "alert_filters",
    sketch = "alert_filters.ino",
    deps = ["//examples/material3/menus:example_runtime"],
)
