// Generated by tools/keyboard_layout/compile.py; do not edit.
#pragma once
#include "roo_windows/keyboard_layout/keyboard_layout.h"
namespace roo_windows {
/// Returns a validated view over static flash layout data.
KeyboardLayout kbPolPLLayout();
}  // namespace roo_windows
