load("//examples:example_build.bzl", "roo_windows_example")

roo_windows_example(
    name = "context_actions",
    sketch = "context_actions.ino",
    deps = ["//examples/material3/menus:example_runtime"],
)
