package(default_visibility = ["//visibility:public"])

exports_files(["example_build.bzl"])

# Compatibility aliases for the former flattened build-only targets. New code
# should use the hierarchical runnable labels in the leaf example packages.
alias(
    name = "material3_app_bar_basic_top_bar_example_build",
    actual = "//examples/material3/app_bar/basic_top_bar",
)

alias(
    name = "material3_app_bar_flexible_top_bar_example_build",
    actual = "//examples/material3/app_bar/flexible_top_bar",
)

alias(
    name = "material3_search_bar_basic_search_example_build",
    actual = "//examples/material3/search_bar/basic_search",
)

alias(
    name = "material3_search_bar_search_app_bar_example_build",
    actual = "//examples/material3/search_bar/search_app_bar",
)

alias(
    name = "material3_badge_notification_count_example_build",
    actual = "//examples/material3/badge/notification_count",
)

alias(
    name = "material3_badge_custom_anchor_example_build",
    actual = "//examples/material3/badge/custom_anchor",
)

alias(
    name = "material3_buttons_pool_actions_example_build",
    actual = "//examples/material3/buttons/pool_actions",
)

alias(
    name = "material3_buttons_compact_controls_example_build",
    actual = "//examples/material3/buttons/compact_controls",
)

alias(
    name = "material3_buttons_toggle_preference_example_build",
    actual = "//examples/material3/buttons/toggle_preference",
)

alias(
    name = "material3_layout_scaffold_adaptive_navigation_example_build",
    actual = "//examples/material3/layout_scaffold/adaptive_navigation",
)

alias(
    name = "material3_pane_layout_equipment_list_detail_example_build",
    actual = "//examples/material3/pane_layout/equipment_list_detail",
)

alias(
    name = "material3_grid_layout_pool_dashboard_example_build",
    actual = "//examples/material3/grid_layout/pool_dashboard",
)

alias(
    name = "material3_lists_settings_example_build",
    actual = "//examples/material3/lists/settings",
)

alias(
    name = "material3_lists_segmented_schedule_example_build",
    actual = "//examples/material3/lists/segmented_schedule",
)

alias(
    name = "material3_lists_navigation_example_build",
    actual = "//examples/material3/lists/navigation",
)

alias(
    name = "material3_lists_selection_controls_example_build",
    actual = "//examples/material3/lists/selection_controls",
)

alias(
    name = "material3_lists_expandable_maintenance_example_build",
    actual = "//examples/material3/lists/expandable_maintenance",
)

alias(
    name = "material3_lists_legacy_baseline_menu_example_build",
    actual = "//examples/material3/lists/legacy_baseline_menu",
)

alias(
    name = "material3_navigation_bar_app_navigation_example_build",
    actual = "//examples/material3/navigation_bar/app_navigation",
)

alias(
    name = "material3_navigation_rail_app_navigation_example_build",
    actual = "//examples/material3/navigation_rail/app_navigation",
)

alias(
    name = "material3_checkbox_alarm_sources_example_build",
    actual = "//examples/material3/checkbox/alarm_sources",
)

alias(
    name = "material3_radio_button_control_density_example_build",
    actual = "//examples/material3/radio_button/control_density",
)

alias(
    name = "material3_switch_connectivity_example_build",
    actual = "//examples/material3/switch/connectivity",
)

alias(
    name = "material3_slider_temperature_setpoint_example_build",
    actual = "//examples/material3/slider/temperature_setpoint",
)

alias(
    name = "material3_slider_stepped_fan_speed_example_build",
    actual = "//examples/material3/slider/stepped_fan_speed",
)

alias(
    name = "material3_slider_centered_balance_example_build",
    actual = "//examples/material3/slider/centered_balance",
)

alias(
    name = "material3_slider_charging_level_example_build",
    actual = "//examples/material3/slider/charging_level",
)

alias(
    name = "material3_slider_inset_icon_example_build",
    actual = "//examples/material3/slider/inset_icon",
)

alias(
    name = "material3_range_slider_quiet_hours_example_build",
    actual = "//examples/material3/range_slider/quiet_hours",
)

alias(
    name = "material3_tabs_status_pages_example_build",
    actual = "//examples/material3/tabs/status_pages",
)

alias(
    name = "material3_tabs_history_filter_example_build",
    actual = "//examples/material3/tabs/history_filter",
)

alias(
    name = "material3_tabs_scrollable_categories_example_build",
    actual = "//examples/material3/tabs/scrollable_categories",
)

alias(
    name = "material3_typography_pool_status_example_build",
    actual = "//examples/material3/typography/pool_status",
)

alias(
    name = "simple_navigation_example_build",
    actual = "//examples/simple/navigation",
)

alias(
    name = "simple_shared_scheduler_example_build",
    actual = "//examples/simple/shared_scheduler",
)

filegroup(
    name = "material3_example_builds",
    srcs = [
        "//examples/material3/app_bar/basic_top_bar",
        "//examples/material3/app_bar/flexible_top_bar",
        "//examples/material3/badge/custom_anchor",
        "//examples/material3/badge/notification_count",
        "//examples/material3/buttons/compact_controls",
        "//examples/material3/buttons/pool_actions",
        "//examples/material3/buttons/toggle_preference",
        "//examples/material3/checkbox/alarm_sources",
        "//examples/material3/grid_layout/pool_dashboard",
        "//examples/material3/layout_scaffold/adaptive_navigation",
        "//examples/material3/lists/expandable_maintenance",
        "//examples/material3/lists/legacy_baseline_menu",
        "//examples/material3/lists/navigation",
        "//examples/material3/lists/segmented_schedule",
        "//examples/material3/lists/selection_controls",
        "//examples/material3/lists/settings",
        "//examples/material3/navigation_bar/app_navigation",
        "//examples/material3/navigation_rail/app_navigation",
        "//examples/material3/pane_layout/equipment_list_detail",
        "//examples/material3/radio_button/control_density",
        "//examples/material3/range_slider/quiet_hours",
        "//examples/material3/search_bar/basic_search",
        "//examples/material3/search_bar/search_app_bar",
        "//examples/material3/slider/centered_balance",
        "//examples/material3/slider/charging_level",
        "//examples/material3/slider/inset_icon",
        "//examples/material3/slider/stepped_fan_speed",
        "//examples/material3/slider/temperature_setpoint",
        "//examples/material3/switch/connectivity",
        "//examples/material3/tabs/history_filter",
        "//examples/material3/tabs/scrollable_categories",
        "//examples/material3/tabs/status_pages",
        "//examples/material3/typography/pool_status",
    ],
)

filegroup(
    name = "all_example_builds",
    srcs = [
        ":material3_example_builds",
        "//examples/flex_layout/01_toolbar",
        "//examples/flex_layout/02_settings_rows",
        "//examples/flex_layout/03_chip_bar",
        "//examples/flex_layout/04_dashboard_grid",
        "//examples/flex_layout/05_holy_grail",
        "//examples/simple/animation",
        "//examples/simple/button",
        "//examples/simple/button_customization",
        "//examples/simple/horizontal_page_host",
        "//examples/simple/icon",
        "//examples/simple/image",
        "//examples/simple/label",
        "//examples/simple/navigation",
        "//examples/simple/shared_scheduler",
    ],
)
