load(":example_build.bzl", "roo_windows_example_build")

roo_windows_example_build(
    name = "material3_app_bar",
    sketch = "material3/app_bar/app_bar.ino",
    include_dir = "material3/app_bar",
)

roo_windows_example_build(
    name = "material3_app_bars",
    sketch = "material3/app_bars/app_bars.ino",
    include_dir = "material3/app_bars",
)

roo_windows_example_build(
    name = "material3_badge",
    sketch = "material3/badge/badge.ino",
    include_dir = "material3/badge",
)

roo_windows_example_build(
    name = "material3_buttons",
    sketch = "material3/buttons/buttons.ino",
    include_dir = "material3/buttons",
)

roo_windows_example_build(
    name = "material3_layout_scaffold",
    sketch = "material3/layout_scaffold/layout_scaffold.ino",
    include_dir = "material3/layout_scaffold",
)

roo_windows_example_build(
    name = "material3_lists",
    sketch = "material3/lists/lists.ino",
    include_dir = "material3/lists",
)

roo_windows_example_build(
    name = "material3_navigation_bar",
    sketch = "material3/navigation_bar/navigation_bar.ino",
    include_dir = "material3/navigation_bar",
)

roo_windows_example_build(
    name = "material3_navigation_rail",
    sketch = "material3/navigation_rail/navigation_rail.ino",
    include_dir = "material3/navigation_rail",
)

roo_windows_example_build(
    name = "material3_selectors",
    sketch = "material3/selectors/selectors.ino",
    include_dir = "material3/selectors",
)

roo_windows_example_build(
    name = "material3_slider",
    sketch = "material3/slider/slider.ino",
    include_dir = "material3/slider",
)

roo_windows_example_build(
    name = "material3_tabs",
    sketch = "material3/tabs/tabs.ino",
    include_dir = "material3/tabs",
)

roo_windows_example_build(
    name = "material3_typography",
    sketch = "material3/typography/typography.ino",
    include_dir = "material3/typography",
)

filegroup(
    name = "material3_example_builds",
    srcs = [
        ":material3_app_bar_example_build",
        ":material3_app_bars_example_build",
        ":material3_badge_example_build",
        ":material3_buttons_example_build",
        ":material3_layout_scaffold_example_build",
        ":material3_lists_example_build",
        ":material3_navigation_bar_example_build",
        ":material3_navigation_rail_example_build",
        ":material3_selectors_example_build",
        ":material3_slider_example_build",
        ":material3_tabs_example_build",
        ":material3_typography_example_build",
    ],
)
