load(":example_build.bzl", "roo_windows_example_build")

roo_windows_example_build(
    name = "material3_app_bar_basic_top_bar",
    sketch = "material3/app_bar/basic_top_bar/basic_top_bar.ino",
    include_dir = "material3/app_bar/basic_top_bar",
)

roo_windows_example_build(
    name = "material3_app_bar_flexible_top_bar",
    sketch = "material3/app_bar/flexible_top_bar/flexible_top_bar.ino",
    include_dir = "material3/app_bar/flexible_top_bar",
)

roo_windows_example_build(
    name = "material3_search_bar_basic_search",
    sketch = "material3/search_bar/basic_search/basic_search.ino",
    include_dir = "material3/search_bar/basic_search",
)

roo_windows_example_build(
    name = "material3_search_bar_search_app_bar",
    sketch = "material3/search_bar/search_app_bar/search_app_bar.ino",
    include_dir = "material3/search_bar/search_app_bar",
)

roo_windows_example_build(
    name = "material3_badge",
    sketch = "material3/badge/badge.ino",
    include_dir = "material3/badge",
)

roo_windows_example_build(
    name = "material3_buttons",
    sketch = "material3/buttons/buttons.ino",
    include_dir = "material3/buttons",
)

roo_windows_example_build(
    name = "material3_layout_scaffold",
    sketch = "material3/layout_scaffold/layout_scaffold.ino",
    include_dir = "material3/layout_scaffold",
)

roo_windows_example_build(
    name = "material3_lists",
    sketch = "material3/lists/lists.ino",
    include_dir = "material3/lists",
)

roo_windows_example_build(
    name = "material3_navigation_bar_app_navigation",
    sketch = "material3/navigation_bar/app_navigation/app_navigation.ino",
    include_dir = "material3/navigation_bar/app_navigation",
)

roo_windows_example_build(
    name = "material3_navigation_rail_app_navigation",
    sketch = "material3/navigation_rail/app_navigation/app_navigation.ino",
    include_dir = "material3/navigation_rail/app_navigation",
)

roo_windows_example_build(
    name = "material3_selectors",
    sketch = "material3/selectors/selectors.ino",
    include_dir = "material3/selectors",
)

roo_windows_example_build(
    name = "material3_slider",
    sketch = "material3/slider/slider.ino",
    include_dir = "material3/slider",
)

roo_windows_example_build(
    name = "material3_tabs_status_pages",
    sketch = "material3/tabs/status_pages/status_pages.ino",
    include_dir = "material3/tabs/status_pages",
)

roo_windows_example_build(
    name = "material3_tabs_history_filter",
    sketch = "material3/tabs/history_filter/history_filter.ino",
    include_dir = "material3/tabs/history_filter",
)

roo_windows_example_build(
    name = "material3_tabs_scrollable_categories",
    sketch = "material3/tabs/scrollable_categories/scrollable_categories.ino",
    include_dir = "material3/tabs/scrollable_categories",
)

roo_windows_example_build(
    name = "material3_typography",
    sketch = "material3/typography/typography.ino",
    include_dir = "material3/typography",
)

filegroup(
    name = "material3_example_builds",
    srcs = [
        ":material3_app_bar_basic_top_bar_example_build",
        ":material3_app_bar_flexible_top_bar_example_build",
        ":material3_badge_example_build",
        ":material3_buttons_example_build",
        ":material3_layout_scaffold_example_build",
        ":material3_lists_example_build",
        ":material3_navigation_bar_app_navigation_example_build",
        ":material3_navigation_rail_app_navigation_example_build",
        ":material3_selectors_example_build",
        ":material3_slider_example_build",
        ":material3_search_bar_basic_search_example_build",
        ":material3_search_bar_search_app_bar_example_build",
        ":material3_tabs_history_filter_example_build",
        ":material3_tabs_scrollable_categories_example_build",
        ":material3_tabs_status_pages_example_build",
        ":material3_typography_example_build",
    ],
)
