load("//examples:example_build.bzl", "roo_windows_example")

roo_windows_example(
    name = "nested_settings",
    sketch = "nested_settings.ino",
    deps = ["//examples/material3/menus:example_runtime"],
)
