load("//examples:example_build.bzl", "roo_windows_example")

roo_windows_example(
    name = "rounded_scrolling",
    sketch = "rounded_scrolling.ino",
    deps = ["//examples/material3/menus:example_runtime"],
)
