load("//examples:example_build.bzl", "roo_windows_example")

roo_windows_example(
    name = "operating_mode",
    sketch = "operating_mode.ino",
    deps = ["//examples/material3/menus:example_runtime"],
)
