name: CI

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: dejwk/roo_testing/.github/workflows/client-ci.yml@953eed22666e4148b687bae5ecdbebe1b9350422 # roo_testing 2.0.0
    with:
      profiles: '["arduino"]'
      system_packages: libx11-dev libjpeg-dev libpng-dev zlib1g-dev
